### ISSUE TITLE
get 3d pose rotation angle ?

### ISSUE THREAD

**Issue by luoww1992** [isarandi/poseviz#3]
i notice you use mayavi,   can we get the 3d pose rotation angle  with parent-children by this project or other module ?
i try to shoe the result 3d pose in UE, can you give me some advices ? 
maybe it needs to change to smpl pose ?

**Comment by isarandi** [comment]
Thanks for your interest! This project just visualizes points connected by edges. Joint rotations are not computed or used. You'd need to perform inverse kinematics to compute rotations.
