### ISSUE TITLE
Poseviz import fails on improc import

### ISSUE THREAD

**Issue by nikitax75** [isarandi/poseviz#5]
Hello there,

First of all, thanks for the nice work, this looks really impressive and sort of unique! 

On my setup, demo.py fails at `import poseviz` because `improc` cannot be imported as the package is not found. Tried to look everywhere for what improc could be and could not find anything on public repositories. 

https://github.com/isarandi/poseviz/blob/c3d0666633530aaa095f821770bed263d55baadc/poseviz/poseviz.py#L12

Environment:

- Ubuntu 20.04
- python 3.8.10
- poseviz head (0.1.3) installed with pip (Anaconda install was unsuccessful)
- mayavi 4.8.1 installed via pip (no compilation errors on my platform)

Any idea what could be wrong? 

Thanks again

**Comment by nikitax75** [comment]
Actually, found the improc source on another of your projects, missing file maybe?

**Comment by isarandi** [comment]
Fixed in the latest version! Thanks for the bug report.
