### ISSUE TITLE
No module named 'cameralib'

### ISSUE THREAD

**Issue by torsten-wilhelm** [isarandi/poseviz#6]
I installed poseviz with: 
`pip install git+https://github.com/isarandi/poseviz.git`
and get "No module named cameralib" at the import statement. 

In the README.md, a camera is created by `camera = poseviz.Camera(...)`
That doesn't work neither.

**Comment by isarandi** [comment]
Thanks, this should be fixed now.

I've recently factored out the `cameralib` to its own package/repo (https://github.com/isarandi/cameralib). Now if you pip install this, it should automatically install cameralib as a dependency.

**Comment by torsten-wilhelm** [comment]
Thank you!
